language: node_js
node_js: "10.15"
cache: yarn

_production-env: &production-env
  ENVIRONMENT: production
  RANCHER_CLUSTERID: c-gxsr7

# _staging-env: &staging-env
#   ENVIRONMENT: staging
#   RANCHER_CLUSTERID: c-rc5kp

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    <<: *production-env

# _staging-job: &staging-job
#   stage: staging
#   name: SERVICE_NAME
#   script: scripts/deploy.js SERVICE_NAME
#   install: skip
#   env:
#     <<: *staging-env

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  # - name: staging-started
  #   if: tag is present
  # - name: staging
  #   if: tag is present
  # - name: staging-finished
  #   if: tag is present

jobs:
  include:
    - stage: test
      env:
        NODE_ENV: test

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env:
        <<: *production-env

    # - stage: staging-started
    #   name: Deployment Started
    #   script: npx @base-cms/website-deployment-tool notify-started
    #   install: skip
    #   env:
    #     <<: *staging-env

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - <<: *production-job
      name: Web Service
      script: scripts/deploy.js web
    # - <<: *staging-job
    #   name: Web Service
    #   script: scripts/deploy.js web

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env:
        <<: *production-env

    # - stage: staging-finished
    #   name: Deployment Finished
    #   script: npx @base-cms/website-deployment-tool notify-finished
    #   install: skip
    #   env:
    #     <<: *staging-env
